---
title: ""
---

**Data Ethics Across the Disciplines** was a discussion series hosted by the [University of Pittsburgh Library System's](https://library.pitt.edu/), Digital Scholarship Services during Spring 2024. **Panel event recordings are now available** under [Community Resources] below.

The Spring 2024 Data Ethics series surfaced more questions than it resolved and made clear the need for continued conversations around how we as researchers, students, and instructors at Pitt navigate ethical data and digital research issues. 

**Stay in touch** by joining the [Interdisciplinary Data Ethics @ Pitt community of practice](https://teams.microsoft.com/l/team/19%3AbhP6sRCqYuQJpQ0dXBruuC6h9svwRH4rW6KFKJCTYR01%40thread.tacv2/conversations?groupId=da3e92e6-025d-4371-9893-648d8d2a41a4&tenantId=9ef9f489-e0a0-4eeb-87cc-3a526112fd0d)! *(Open to Pitt community members; login with your Pitt credentials.)*

You are also welcome to [subscribe to the Library Digital Scholarship Services newsletter](https://confirmsubscription.com/h/t/DF8BAC3FE84F3E2D) to be notified of any future data ethics events hosted by the University Library System.

-----------------------------------------------------------------------

*About the series:* What ethical concerns have you dealt with around data collection or creation in your field? Are you interested in sharing your experience confronting ethical challenges in working with different kinds of data? Have you been seeking opportunities to connect with other researchers facing similar data-sharing issues, or are you looking for collaborators to tackle interdisciplinary data analysis problems? See a list of [Past Events] below for a summary of the conversations held on these topics.

See also the [Related Events] section below for Spring 2024 talks from our partners at the [Research, Ethics and Society Initiative (RESI)](https://www.research.pitt.edu/about/research-ethics-and-society-initiative).

------------------------------------------------------------------------

## Community Resources

### Event Recordings

*Pitt login required to view.*

-   [Global Perspectives on Ethical Data Management](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=50a28121-077d-45ec-8388-b19c001f5187&start=0) (February 23, 2024)
-   [Social Media Data Ethics](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=43b18fab-64d2-4cce-88a3-b19c00205dac&start=0) (February 26, 2024)
-   [Pedagogy, Data Governance, and Predictive Analytics](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=05d0719b-e3e1-4b17-8ffc-b19c001f5cec&start=0) (March 1, 2024)
-   [Community-centered Ethics for Digital Cultural Heritage Materials](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6f1aebd8-ca6f-4e37-a4be-b19c001f5ccd&start=0) (March 4, 2024)
-   [Truth vs Authenticity in the Digital Representation of Text Data](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=37ea5764-c7b0-4852-8497-b19c0021f06f&start=0) (March 22, 2024)
-   [Ethical Tensions between Privacy and Access for Human-Subjects Data](https://pitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=888cdd5d-57b5-4d84-9e47-b19c001f5ce1&start=0) (March 25, 2024)

### Community Bibliography

Find ethical frameworks, recommended resources, and relevant literature in the [community-generated bibliography here](https://www.zotero.org/groups/2472109/uls_dss/collections/RRJ4IJR2).


## Past Events

### Closing Unconference

**Presented jointly by the [University Library System (ULS)](https://library.pitt.edu/) and the [Research, Ethics and Society Initiative (RESI)](https://www.research.pitt.edu/about/research-ethics-and-society-initiative)**

📅 Tuesday, April 2, 2024    🕛 12--2pm

The University Library System's [Data Ethics Across the Disciplines discussion series](https://dssatpitt.github.io/data-ethics-across-disciplines/) wraps up with a final loosly-structured unconference conversation! Join us as we debrief following the six panel discussions on a variety of ethical data creation, use, and sharing topics. What have we learned through this semester's conversations? Where do we want to collectively go next as a community of practice around data ethics at Pitt? Connect with fellow scholars interested in data ethics in this final series event, as we summarize, synthesize, and plan for future collaborations around data ethics across disciplines.

A light lunch will be provided for participants. **Seats are limited for this unconference; please register only with a strong intention to attend.** We ask registrants to confirm their availability to attend 48 hours prior to this event and cancel your registration if you are no longer able to attend, to allow someone else to take your seat.

[✏ Register](https://pitt.libcal.com/event/12121356)

### Ethical Tensions between Privacy and Access for Human-Subjects Data

📅 Monday, March 25, 2024    🕛 12--1:30pm

Recent policies from funders and publishers demand, justifiably, public access to data as a research output on par with Open Access publications. Indeed, data sharing is necessary even for validation and replication of findings. However, sharing data associated with human subjects is complexified by the competing need to respect the personal rights of those same subjects, especially the rights to privacy and informed consent. How can researchers share their observations without betraying the subjects' rights, since those observations necessarily contain sensitive information?

This discussion will approach the ethical questions tied to sharing human-subjects data in two broad areas of inquiry: biomedical research, and social science research.

In the biomedical setting, seemingly "anonymized" demographic details, and even precise genetic markers, may be used to determine a patient's identity if not carefully protected, all while crossing institutional and vendor boundaries. Another recently growing concern is the training and deployment of AI models without patient consent.

Meanwhile, social scientists studying social movements are confronted with quite different, but still related, quandaries: what confidentiality agreements and informed consent procedures to protect research participants should we utilize when collecting data from online forums? And how should we handle collection of data from various countries, involving different political climates and laws that may affect the privacy and security of research participants?

This discussion will focus on the inherent tensions between data access, due diligence in de-identification methods, financial motivations, and current practices. Examining issues including ethical collection, storage, sharing, and reproducibility provides an opportunity to interrogate frictions in this complex data environment.

**Speakers:**

-   **Ravi Patel**, Lead Innovation Advisor in the School of Pharmacy
-   **Amin Rahimian**, Assistant Professor of Industrial Engineering
-   **Hanning Wang**, PhD Student in Sociology

[✏ Register](https://pitt.libcal.com/event/12031174)

### Truth versus Authenticity

**Exploring the Ethical Paradoxes inherent in the Digital Representation of Text Data.**

📅 Friday, March 22, 2024    🕛 12--1:30pm

This interactive conversation will explore ethical questions related to the digital representation of texts. Mark DiMauro and Joshua Calandrella will discuss questions of translating and digitally representing sacred texts, considering both the mystic implications of technology and the ethical concerns that arise when artificial intelligence (AI) and other generative technology manipulates language and expresses linguistic patterns as mathematical datasets. What new and meaningful arrangements (datasets, translations, etc.) might become possible if these are generated with a reverence for the power traditionally associated with sacred and esoteric reading practices? Raja Adal will speak to these ethical questions as they relate to text encoding practices and consider how we might incorporate an ethical lens when working with other types of historical text data.

What kinds of textual materials do you work with in your disciplinary practices? How might researchers address the challenges of translating and digitally representing texts and grapple with concerns of distorting meaning? How might we anticipate and prevent accidental harm that could result from sharing text data openly online in an era of rapidly evolving AI algorithms?

Join us for this conversation to learn more and connect with other Pitt community members interested in ethical approaches to textual data.

**Speakers:**

-   **Mark DiMauro**, Assistant Professor of Digital Humanities (UPJ)
-   **Joshua Calandrella**, Adjunct Professor of Composition (UPJ)
-   **Raja Adal**, Associate Professor of History

[✏ Register](https://pitt.libcal.com/event/12031155)

### Community-centered Ethics for Digital Cultural Heritage Materials

**A dialogue on the tensions between consent, preservation, and access.**

📅 Monday, March 4, 2024    🕛 12--1:30pm

This panel discussion highlights the ethical issues of privacy, consent, and ownership of digitized cultural heritage materials held in library and museum collections around the globe. Megan Massanelli, Carolyn Friedrich, and David Grinnell will speak to the process of digitizing local LGBTQIA+ community publications where concerns are centered on informed consent, assumptions about anonymity in the original print medium, the right to be forgotten online, and community voices in those decisions about what is shared online. Jesse Obert will speak to his work with Greek material culture held outside of Greece in European and American museums, considering the absence of the Greek voice during the ongoing digitization of those materials as well as the ways in which European colonialism continues to exclude Greeks from their own cultural heritage, especially in the digital space.

How might researchers, educators, and scholars approach issues related to the access and use of digital surrogates? How might we advocate for community voices in the digitization, storage, and publication of cultural heritage materials? Join us for this conversation to learn more and connect with other Pitt community members interested in ethical approaches to cultural heritage data.

**Speakers:**

-   **Megan Massanelli**, Archives & Special Collections Engagement and Outreach Librarian (University Library System)
-   **Carolyn Friedrich**, Digital Collections Coordinator (University Library System)
-   **David Grinnell**, Coordinator of Archives and Manuscripts (University Library System)
-   **Jesse Obert**, Digital World History Postdoctoral Associate (World History Center)

[✏ Register](https://pitt.libcal.com/event/12031147)

### Pedagogy, Data Governance, and Predictive Analytics

**A conversation on institutional data practices at Pitt.**

📅 Friday, March 1, 2024    🕛 12--1:30pm

This panel assembles perspectives from multiple units across Pitt to explore predictive analytics, institutional data practices, data governance, and their pedagogical and ethical implications within a rapidly evolving technology landscape.

Amanda Brodish will discuss the use of predictive analytics as part of the Pathways Student Success and Advising platform, providing an overview of the process used to engage faculty, students, and administrators in the use of predictive analytics; the development of a process allowing students to opt out; and the specific data points that are (and are not) included in the predictive analytics models. Michael Madison will speak to ongoing work at Pitt around data governance models and policies for institutional data. Gordon Mitchell will explore the question, how can an understanding of predictive analytics enhance data literacy for Pitt students preparing to work in our networked society?

Join us for an engaging discussion to learn more and connect with other Pitt community members interested in data ethics.

**Speakers:**

-   **Amanda Brodish**, Associate Vice Provost for Data Analytics
-   **Michael Madison**, Professor of Law and John E. Murray Faculty Scholar
-   **Gordon Mitchell**, Associate Professor of Communication and Associate Professor of Clinical and Translational Science

[✏ Register](https://pitt.libcal.com/event/12031140)

### Social Media Data Ethics

**Grounding our Values and Localizing ~~Best~~ Better Practices.**

📅 Monday, February 26, 2024    🕛 12--1:30pm

This event aims to bring together members of the Pitt community for an interactive conversation regarding ethics and social media data. Two presenters - Lara Putnam and Elise Silva - will summarize the range of best practice guides that have already been developed on this topic and share a curated, annotated set of these external resources as a starting point with the hope of opening conversation. They hope specifically to localize this discussion around what tools, resources, and/or potential curricular vehicles Pitt teachers, mentors, and scholars feel they need in this rapidly changing arena. Our third presenter - Frances Corry - will then explore how values/ethics are expressed and mobilized by social media platform employees as they handle user data in the platform sunsetting process, providing another framework for thinking through the kinds of data that are generated and stored in social media platforms.

How are social media data used or generated in your disciplinary practices? What ethical concerns might we face across disciplinary boundaries when working with social media data? Join us for this conversation to learn more and connect with other Pitt community members interested in ethical approaches to social media data.

**Speakers:**

-   **Lara Putnam**, UCIS Professor (History), Director of the Global Studies Center, and Co-lead for the Civic Resilience Initiative of the Pitt Disinformation Lab
-   **Elise Silva**, Postdoctoral Associate with Pitt Cyber's Disinformation Lab and the Western PA Writing Project
-   **Frances Corry**, Assistant Professor of Information Culture and Data Stewardship

[✏ Register](https://pitt.libcal.com/event/12031138)

### Global Perspectives on Ethical Data Management

**A cross-disciplinary workshop on international data projects and cultural approaches to data harm.**

📅 Friday, February 23, 2024    🕛 12--1:30pm

This interactive discussion will explore the benefits and challenges inherent to multi-institutional and international projects that represent diverse disciplinary and cultural data practices. Speaking from varied roles on such projects or programs, presenters will address what it means to take a global cultural approach to data ethics, given the nature of working with data produced by different communities and navigating the complex landscape of international policies and cultural expectations.

A facilitated discussion will follow speaker introductions, aimed at sharing best practices and generating strategies for building global cultural competencies, identifying resources available to support global digital research at Pitt, and creating connections across disciplinary boundaries.

What might it look like for researchers to take an ethical perspective on global data harm when developing international collaborations? What is involved when translating policies to practice and coordinating complex research projects? How might we address implicit power relations, funding inequities, and the continued impact of colonialism on the data produced by our research and other activities? Join us for this conversation to learn more and connect with other Pitt community members interested in global approaches to data ethics.

**Speakers**:

-   **Ruth Mostern**, Professor of History and Director of the World History Center
-   **Stephen Wludarski**, Program Manager for the National Consortium for Teaching about Asia (NCTA) Pittsburgh, Asian Studies Program
-   **Victoria Sterling**, Former Grant Manager for the Geography of Philosophy Project

[✏ Register](https://pitt.libcal.com/calendar/today/dataethics-globaldatamanagement)

### Interdisciplinary Data Ethics Unconference

📅 Friday, February 2, 2024    🕛 12--2pm\
Presented jointly by the [University Library System (ULS)](https://library.pitt.edu/) and the [Research, Ethics and Society Initiative (RESI)](https://www.research.pitt.edu/about/research-ethics-and-society-initiative)

The Data Ethics Across the Disciplines discussion series kicks off with a mini-unconference! Join us for an engaging conversation on the ethical data creation, use, and sharing challenges faced by researchers and students at Pitt. Meet up with fellow scholars interested in data ethics and with panelists from the Data Ethics Across the Disciplines series, as we collaboratively determine a discussion agenda and split up into small and large group discussions on various topics, such as:

-   ethical data collection practices
-   evaluating data storage and sharing platforms through an ethics lens
-   tensions between data privacy and sharing
-   data harm
-   teaching data ethics in the classroom
-   ethics of reproducibility

A light lunch will be provided for participants. **Seats are limited for this unconference; please register only with a strong intention to attend.** We ask registrants to confirm their availability to attend 48 hours prior to this event and cancel your registration if you are no longer able to attend, to allow someone else to take your seat.

## Related Events

*From our partners around campus, such as the [Research, Ethics and Society Initiative (RESI)](https://www.research.pitt.edu/events) and the [World History Center](https://www.worldhistory.pitt.edu/); visit links for location, registration, and more:*

### Hidden Labor & Hidden Costs

📅 Wednesday, February 14, 2024    🕙 10am--12pm

> In our day-to-day interactions with apps and websites, we are often only privy to the up-front, monetary costs and user interfaces. When we order a mug from Amazon, or like a picture of puppies on Facebook, we enjoy the ease and entertainment of these services, but the inner workings that make these transactions so seamless and satisfying are hidden from us. We are promised and have come to expect technology to ensure our package arrives in two days or that our latest post is seen by our followers, but we are rarely compelled to question the "how" of these operations. What might we uncover if we dared to look into the mechanisms that make our lives so convenient and efficient? During this session, attendees will collectively explore questions about costs, labor and automation, and critically consider the true price of the technological infrastructure that supports our ways of living.

[✏ More info and register](https://www.research.pitt.edu/events/hidden-labor-hidden-costs)

### Building Partnerships to Advance Ethical Research: Collaborators, Communities & Companies

📅 Wednesday, February 28, 2024    🕙 10am--4pm

> As research teams become larger and more complex, forging effective partnerships to ensure the ethical conduct of research has become more challenging. Yet creating successful collaborations to ensure the responsible conduct of research is crucial at all stages of the research process. Researchers need to build a team that successfully integrates investigators, research staff, and trainees in the responsible conduct of research. They need to be able to partner respectfully in community-engaged and community-led research, building alliances to advance equity, inclusion, and cross-learning. And in creating relationships with funders and companies to develop and apply the research, researchers need to fulfill ethical duties including disclosure and managing conflicts of interest and commitment.
>
> This conference will discuss ways to build strong partnerships with investigators, communities, clinical research professionals, and companies to promote the ethical conduct and translation of research. Speakers will consider the elements of successful collaboration that promote research integrity, inclusivity, mutual respect, and accountability in the conduct of research.

[✏ More info and register](https://www.research.pitt.edu/events/building-partnerships-advance-ethical-research-collaborators-communities-companies)

### Shepherding Neurotechnology through Regulatory Review

📅 Wednesday, February 28, 2024    🕞 3:30--5:30pm

> This talk is hosted by the Pitt-CMU Rehab Neuroengineering Laboratory and co-sponsored by the Research, Ethics and Society Initiative of Pitt Research.

[✏ More info and register](https://www.research.pitt.edu/events/shepherding-neurotechnology-through-regulatory-review)

### Inequality & the Environment: Moving from Science to Action that Advances Environmental Justice and Health Equity

📅 Friday, March 1, 2024    🕐 1--2pm

> Lara Cushing, PhD, MPH\
> Jonathan and Karin Fielding Presidential Chair in Health Equity and\
> Assistant Professor of Environmental Health Sciences\
> University of California, Los Angeles
>
> Abstract: People of color are more likely to breathe dirty air, drink contaminated water, and live near hazardous waste sites, industrial agriculture operations, and other sources of pollution. Accelerating climate change is having additional disproportionate effects on minoritized populations. This talk will discuss structural determinants of environmental health disparities and community-engaged research to develop decision support tools that advance environmental justice.

[✏ More info and register](https://www.research.pitt.edu/events/inequality-environment-moving-science-action-advances-environmental-justice-and-health-equity)

### Read & Discuss: The Dangerous Art of Text Mining

📅 Monday, March 18, 2024    🕝 2:30--4pm

> Join the World History Center for a discussion about [*The Dangerous Art of Text Mining: A Methodology for Digital History*](https://www.cambridge.org/core/books/dangerous-art-of-text-mining/C07F637BB12F7D89CF9295F02EF44905) by Jo Guldi. A limited number of copies of the book will be made available before the event. The book is available to read online [here](https://www.cambridge.org/core/books/dangerous-art-of-text-mining/C07F637BB12F7D89CF9295F02EF44905#fndtn-contents).
>
> *The Dangerous Art of Text Mining* celebrates the bold new research now possible because of text mining: the art of counting words over time. However, this book also presents a warning: without help from the humanities, data science can distort the past and lead to perilous errors. The book opens with a rogue's gallery of errors, then tours the ground-breaking analyses that have resulted from collaborations between humanists and data scientists. Jo Guldi explores how text mining can give a glimpse of the changing history of the past---for example, how quickly Americans forgot the history of slavery. Textual data can even prove who was responsible in Congress for silencing environmentalism over recent decades. The book ends with an impassioned vision of what text mining in defence of democracy would look like, and why humanists need to be involved.

[✏ More info and register](https://calendar.pitt.edu/event/read_discuss_the_dangerous_art_of_text_mining)

### The Black Prisoners of Stateville: Race, Research, and Reckoning at the Origin of Precision Medicine

📅 Friday, March 22, 2024    🕛 12--1pm

> James Tabery, PhD, MA\
> Professor of Philosophy\
> Center for Health Ethics, Arts & Humanities\
> University of Utah
>
> Abstract: The modern science of pharmacogenomics, which set the stage for precision medicine, was born in a prison outside Chicago 70 years ago. Clinical researchers with the US Army and the University of Chicago used Black prisoners at the Stateville Penitentiary, as well as their family members and other Black community members in the vicinity, to determine why some people have a dangerous reaction to antimalarial drugs. The research, in hindsight, is shocking. There is a large body of research ethics scholarship that reflects on the controversial research conducted at Stateville; oddly, however, the standard version of this story is that the research involved only white prisoners. In this talk, Dr. Tabery will share what he and his colleagues have uncovered about the research involving the Black participants, ask why their contribution to the famous history of precision medicine has been omitted, and consider appropriate ways to remember a community of people whose bodies and blood were used to give rise to precision medicine.

[✏ More info and register](https://www.research.pitt.edu/events/black-prisoners-stateville-race-research-and-reckoning-origin-precision-medicine)

### Collective Futures

📅 Wednesday, March 27, 2024    🕙 10am--12pm

> As humans, we are inherently future-oriented. Our dreams and hopes fuel our lives and livelihoods. When you think of the words "future" and "progress", what comes to mind? Our popular media and rhetoric is filled with narratives that essentially equate progress and the future with the emergence of superior technology that will either solve all human problems or destroy humanity entirely. Who drives these dominant visions of the future that we are steering toward? How might we conceptualize future possibilities, outside of a framework of technological inevitability and centrality? For example, what might future families, communities, gardens, and schools look and feel like? During this session, we will collectively explore our questions about progress, and imagine education futures rooted in justice and freedom.

[✏ More info and register](https://www.research.pitt.edu/events/collective-futures)

### Ethical Considerations for AI in Healthcare

📅 Friday, April 5, 2024    🕛 12--1pm

> Kellie N. Owens, PhD\
> Assistant Professor of Population Health\
> New York University
>
> Abstract: This talk will explore ethical considerations that arise in the development and deployment of artificial intelligence (AI) and machine learning in healthcare, including equity, fairness, privacy, safety, and transparency. Based on initial findings from two different empirical bioethics research projects, Dr. Owens will first explore how to ethically and effectively govern AI systems and models in healthcare settings based on in-depth interviews with key stakeholders including data scientists, clinicians, and regulators. She will then examine how patient-facing generative AI tools such as automated clinical documentation and AI-drafted patient messaging in online health portals may affect trust and empathy between clinicians and patients. Both projects seek to guide healthcare systems in navigating the ethical complexities of adopting new technologies, ensuring that advancements in AI serve to strengthen, rather than erode, the foundational trust in our healthcare systems and patient-clinician relationships.

[✏ More info and register](https://www.research.pitt.edu/events/ethics-using-ai-medicine)

## Call for Participation

***The Call for Participation is now closed.***

This CFP outlines an opportunity for all Pitt community members---including staff, students, researchers, and instructors---to contribute to a cross-disciplinary conversation around research ethics pertaining to data collection, creation, analysis, organization, storage, sharing, and other aspects of data-driven scholarship.

As machine learning technology continues to develop, as data sharing policies and funder mandates evolve, and as the lives and work of researchers and students are increasingly implicated in the growing datafication of our society, conversations around the ethical creation and use of data---defined broadly---are vital to the success of the university's mission. To promote increased dialogue across disciplines regarding the ethical issues we face in collecting, analyzing, and sharing data, the Digital Scholarship Services team within the University Library System will facilitate a series of interdisciplinary talks, moderated panel discussions, and unconference-style events around the theme of data ethics during the Spring 2024 semester. This series aims to enable Pitt community members to collaboratively explore ethical issues impacting data-driven scholarship across various departments and fields.

[Read the full CFP](https://pitt-my.sharepoint.com/:b:/g/personal/ras545_pitt_edu/ETwAdtwmo5lLos9wMleE49cBg1fSNNgXhvmu2fHLaOUc_A).

## Contact

For questions or comments, please write to [rachel.starry\@pitt.edu](mailto:rachel.starry@pitt.edu).
